[FIX] ol_product_system_stock (Bool object has no attribute)
Made the previous fix more robust since if channel is not found it could cause a "AttributeError: 'bool' object has no attribute 'complete_name'" when the next code is called so this change should prevent another error.