[FIX] helpdesk_fieldservice (Error if user doesn't have helpdesk access)
This fixes an error if user doesn't have helpdesk access, when they try to open a contact they get the following error:
File "/opt/odoo/v12/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 710, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo/v12/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Element '<button name="action_open_helpdesk_ticket">' cannot be located in parent view

Error context:
View `res.partner.form.ticket.context`
[view_id: 3257, xml_id: helpdesk_fieldservice.res_partner_form_ticket_context, model: res.partner, parent_id: 113]