[FIX] Add missing index, otherwise it complains for tuple index out of range
Traceback log:
  res = super()._action_done(cancel_backorder=cancel_backorder)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 130, in _action_done
    self.get_svl_ids(move)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 120, in get_svl_ids
    self.get_ji_ids(move, svl_ids)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 34, in get_ji_ids
    if svl_id[3].product_id.tracking == "lot":
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
IndexError: tuple index out of range